name: VaultSlip CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create minimal .env for CI
        run: |
          cat > .env <<'ENV'
          CHAINS=ETH,POLY,CELO
          RPC_URI_ETH=https://eth.llamarpc.com
          RPC_URI_POLY=https://polygon-rpc.com
          RPC_URI_CELO=https://forno.celo.org
          EXECUTE_LIVE=false
          HOT_WALLET_MNEMONIC="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
          HOT_WALLET_COUNT=1
          SWEEP_TO=0xf8AD2786102b64083E49b1e84B70cE3CaCC545de
          ETHERSCAN_API_KEY=dummy
          POLYGONSCAN_API_KEY=dummy
          CELOSCAN_API_KEY=dummy
          ENV
          echo "Wrote C:\Users\Johnny\Projects\VaultSlip/.env"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("vaultslip")
          print("vaultslip import OK")
          PY

      - name: Run pytest (non-fatal for now)
        run: pytest -q
        continue-on-error: true

      - name: CI summary
        if: always()
        run: echo "CI completed (pytest allowed to fail for now)" >> 
