name: VaultSlip CI (sanity)
on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sanity
        run: |
          python -V
          echo "PWD=C:\Users\Johnny\Projects\VaultSlip"
          ls -la

      - name: Upload logs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            logs/**
            data/review/**
          if-no-files-found: ignore
