name: VaultSlip CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create minimal .env for CI
        run: |
          cat > .env <<'ENV'
          CHAINS=ETH,POLY,CELO
          RPC_URI_ETH=https://eth.llamarpc.com
          RPC_URI_POLY=https://polygon-rpc.com
          RPC_URI_CELO=https://forno.celo.org
          EXECUTE_LIVE=false
          HOT_WALLET_MNEMONIC="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
          HOT_WALLET_COUNT=1
          SWEEP_TO=0xf8AD2786102b64083E49b1e84B70cE3CaCC545de
          ETHERSCAN_API_KEY=dummy
          POLYGONSCAN_API_KEY=dummy
          CELOSCAN_API_KEY=dummy
          ENV
          echo "Wrote C:\Users\Johnny\Projects\VaultSlip/.env"

      - name: Install dependencies (best effort)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest || true

      - name: Smoke import (non-fatal)
        run: |
          python - <<'PY'
          import importlib.util
          ok = importlib.util.find_spec("vaultslip") is not None
          print("find_spec(vaultslip) ->", ok)
          try:
              import vaultslip
              print("import vaultslip -> OK")
          except Exception as e:
              print("import vaultslip -> WARN:", e)
          PY
        continue-on-error: true

      - name: Run pytest (non-fatal for now)
        run: pytest -q || true

      - name: CI summary
        if: always()
        run: echo "CI completed (deps/import/tests allowed to fail for now)" >> \
